### ISSUE TITLE
[Question] Is mediation supported?

### ISSUE THREAD

**Issue by neuronix** [distriqt/ANE-IronSource#13]
Hi guys,

Does this ANE include mediation for all networks? If not, which networks are included?

It seems pretty small in size but there are the FB Audience Network files that suggest FAN is supported.

Thanks!

**Comment by marchbold** [comment]
You should be able to use any of the mediators from Ironsource. 

The facebook audience extension is included as the version from Ironsource is broken. Documentation on using it is in the wiki:

https://github.com/distriqt/ANE-IronSource/wiki/m.Mediation---Facebook-Audience

**Comment by neuronix** [comment]
Hi @marchbold, thanks for your quick reply, Ironsource's ANEs are indeed in such a poor state, we will give yours a try! :)

**Comment by sweetnitro** [comment]
Re @marchbold it works like a charm, thanks!

There is only one issue, IronSourceAdMobAdapter_v4.1.6.ane on iOS is provoking a crash at compilation:
Undefined symbols for architecture armv7:
  "_kGADAdSizeLeaderboard", referenced from:
      -[ISAdMobAdapter getBannerSize:] in ISAdMobAdapter(ISAdMobAdapter.o)
  "_kGADAdSizeLargeBanner", referenced from:
      -[ISAdMobAdapter getBannerSize:] in ISAdMobAdapter(ISAdMobAdapter.o)
  "_kGADAdSizeBanner", referenced from:
      -[ISAdMobAdapter getBannerSize:] in ISAdMobAdapter(ISAdMobAdapter.o)
  "_OBJC_CLASS_$_GADExtras", referenced from:
      objc-class-ref in ISAdMobAdapter(ISAdMobAdapter.o)
  "_OBJC_CLASS_$_GADMobileAds", referenced from:
      objc-class-ref in ISAdMobAdapter(ISAdMobAdapter.o)
  "_OBJC_CLASS_$_GADRequest", referenced from:
      objc-class-ref in ISAdMobAdapter(ISAdMobAdapter.o)
  "_OBJC_CLASS_$_GADBannerView", referenced from:
      objc-class-ref in ISAdMobAdapter(ISAdMobAdapter.o)
  "_OBJC_CLASS_$_GADInterstitial", referenced from:
      objc-class-ref in ISAdMobAdapter(ISAdMobAdapter.o)
  "_OBJC_CLASS_$_GADRewardedAd", referenced from:
      objc-class-ref in ISAdMobAdapter(ISAdMobAdapter.o)
  "_kGADAdSizeMediumRectangle", referenced from:
      -[ISAdMobAdapter getBannerSize:] in ISAdMobAdapter(ISAdMobAdapter.o)
  "_GADAdSizeFromCGSize", referenced from:
      -[ISAdMobAdapter getBannerSize:] in ISAdMobAdapter(ISAdMobAdapter.o)
ld: symbol(s) not found for architecture armv7
Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_GADExtras", referenced from:
      objc-class-ref in ISAdMobAdapter(ISAdMobAdapter.o)
  "_OBJC_CLASS_$_GADMobileAds", referenced from:
      objc-class-ref in ISAdMobAdapter(ISAdMobAdapter.o)
  "_OBJC_CLASS_$_GADRewardedAd", referenced from:
      objc-class-ref in ISAdMobAdapter(ISAdMobAdapter.o)
  "_OBJC_CLASS_$_GADBannerView", referenced from:
      objc-class-ref in ISAdMobAdapter(ISAdMobAdapter.o)
  "_OBJC_CLASS_$_GADInterstitial", referenced from:
      objc-class-ref in ISAdMobAdapter(ISAdMobAdapter.o)
  "_OBJC_CLASS_$_GADRequest", referenced from:
      objc-class-ref in ISAdMobAdapter(ISAdMobAdapter.o)
  "_kGADAdSizeBanner", referenced from:
      -[ISAdMobAdapter getBannerSize:] in ISAdMobAdapter(ISAdMobAdapter.o)
  "_kGADAdSizeLargeBanner", referenced from:
      -[ISAdMobAdapter getBannerSize:] in ISAdMobAdapter(ISAdMobAdapter.o)
  "_GADAdSizeFromCGSize", referenced from:
      -[ISAdMobAdapter getBannerSize:] in ISAdMobAdapter(ISAdMobAdapter.o)
  "_kGADAdSizeMediumRectangle", referenced from:
      -[ISAdMobAdapter getBannerSize:] in ISAdMobAdapter(ISAdMobAdapter.o)
  "_kGADAdSizeLeaderboard", referenced from:
      -[ISAdMobAdapter getBannerSize:] in ISAdMobAdapter(ISAdMobAdapter.o)
ld: symbol(s) not found for architecture arm64


Note that without IronSourceAdMobAdapter_v4.1.6.ane admob is not detected by ironsource (on both android & ios). We've also tried with com.distriqt.ironsource.FacebookAudience.ane included (since you are mentioning admob in your documentation).

Do you have an idea how we could fix it?

**Comment by marchbold** [comment]
You need to add several ANEs to support their AdMob implementation. See the docs for more:

https://developers.ironsrc.com/ironsource-mobile/air/admob-mediation-guide/#step-4

There are 5 `com.ironsource.adobeair.google.XXX` type extensions that include the AdMob SDK, which is what the error above referring to as missing.

**Comment by sweetnitro** [comment]
Oh these ANEs were also crashing without your Ironsource ANE but now there are working!
Thanks a lot!
